export const CLIENTS = [
  {
    id: 1,
    name: "Harshit Sharma",
    clientId: "MML-D-10248",
    phone: "******4598",
    status: "Inactive",
    married: false,
    address: "*********** Vasant Kunj, New Delhi",
    owner: "Rohit Kumar",
    branch: "South Extension",
    lastContact: "21/08/26",
    reason: "Negotiating 10% discount",
    gender: "Male",
    area: "South Extension",
    education: "B.Tech",
    incomeLpa: 32,
  },
  {
    id: 2,
    name: "Aditi Gupta",
    clientId: "MML-D-10248",
    phone: "******4598",
    status: "Inactive",
    married: true,
    address: "*********** Vasant Kunj, New Delhi",
    owner: "Rohit Kumar",
    branch: "Rajouri Garden",
    lastContact: "21/08/26",
    reason: "Hand Over, Match confirmed",
    gender: "Female",
    area: "Rajouri Garden",
    education: "MBA - IIM",
    incomeLpa: 45,
  },
  {
    id: 3,
    name: "Aslesha Singh",
    clientId: "MML-D-10248",
    phone: "******4598",
    status: "Active",
    married: false,
    address: "*********** Vasant Kunj, New Delhi",
    owner: "Rohit Kumar",
    branch: "Gurgaon",
    lastContact: "21/08/26",
    reason: "Comparing package benefits",
    gender: "Female",
    area: "Rohini",
    education: "MBA - IIM",
    incomeLpa: 52,
  },
  {
    id: 4,
    name: "Aanchal Verma",
    clientId: "MML-D-10248",
    phone: "******4598",
    status: "Inactive",
    married: true,
    address: "*********** Vasant Kunj, New Delhi",
    owner: "Rohit Kumar",
    branch: "Dubai",
    lastContact: "21/08/26",
    reason: "Advance recieved",
    gender: "Female",
    area: "Dubai",
    education: "MBBS",
    incomeLpa: 60,
  },
  {
    id: 5,
    name: "Khushi Kumari",
    clientId: "MML-D-10248",
    phone: "******4598",
    status: "Inactive",
    married: false,
    address: "*********** Vasant Kunj, New Delhi",
    owner: "Rohit Kumar",
    branch: "South Extension",
    lastContact: "21/08/26",
    reason: "Positive response both sides",
    gender: "Female",
    area: "Rohini",
    education: "B.Com",
    incomeLpa: 28,
  },
  {
    id: 6,
    name: "Disha Dubey",
    clientId: "MML-D-10248",
    phone: "******4598",
    status: "Active",
    married: false,
    address: "*********** Vasant Kunj, New Delhi",
    owner: "Rohit Kumar",
    branch: "Rajouri Garden",
    lastContact: "21/08/26",
    reason: "Negotiating 10% discount",
    gender: "Female",
    area: "Rajouri Garden",
    education: "B.Tech - IIT",
    incomeLpa: 48,
  },
  {
    id: 7,
    name: "Virat Sharma",
    clientId: "MML-D-10248",
    phone: "******4598",
    status: "Active",
    married: false,
    address: "*********** Vasant Kunj, New Delhi",
    owner: "Rohit Kumar",
    branch: "Rajouri Garden",
    lastContact: "21/08/26",
    reason: "Negotiating 10% discount",
    gender: "Male",
    area: "Rajouri Garden",
    education: "B.Tech - IIT",
    incomeLpa: 55,
  },
];
