export const CLIENTS = [
  {
    id: 1,
    name: "Harshit Sharma",
    clientId: "MML-D-10248",
    phone: "******4598",
    status: "Inactive",
    married: false,
    address: "*********** Vasant Kunj, New Delhi",
    owner: "Rohit Kumar",
    branch: "South Extension",
    lastContact: "21/08/26",
    reason: "Negotiating 10% discount",
    gender: "Male",
    area: "South Extension",
    education: "B.Tech",
    incomeLpa: 32,
    probability: "low",
  },
  {
    id: 2,
    name: "Aditi Gupta",
    clientId: "MML-D-10249",
    phone: "******4598",
    status: "Inactive",
    married: true,
    address: "*********** Vasant Kunj, New Delhi",
    owner: "Rohit Kumar",
    branch: "Rajouri Garden",
    lastContact: "21/08/26",
    reason: "Hand Over, Match confirmed",
    gender: "Female",
    area: "Rajouri Garden",
    education: "MBA - IIM",
    incomeLpa: 45,
    probability: "medium",
  },
  {
    id: 3,
    name: "Aslesha Singh",
    clientId: "MML-D-10250",
    phone: "******4412",
    status: "Active",
    married: false,
    address: "*********** Rohini, New Delhi",
    owner: "Rohit Kumar",
    branch: "Gurgaon",
    lastContact: "21/08/26",
    reason: "Comparing package benefits",
    gender: "Female",
    area: "Rohini",
    education: "MBA - IIM",
    incomeLpa: 52,
    probability: "high",
  },
  {
    id: 4,
    name: "Aanchal Verma",
    clientId: "MML-D-10251",
    phone: "******7781",
    status: "Inactive",
    married: true,
    address: "*********** JLT, Dubai",
    owner: "Rohit Kumar",
    branch: "Dubai",
    lastContact: "21/08/26",
    reason: "Advance received",
    gender: "Female",
    area: "Dubai",
    education: "MBBS",
    incomeLpa: 60,
    probability: "medium",
  },
  {
    id: 5,
    name: "Khushi Kumari",
    clientId: "MML-D-10252",
    phone: "******3304",
    status: "Inactive",
    married: false,
    address: "*********** Rohini, New Delhi",
    owner: "Rohit Kumar",
    branch: "South Extension",
    lastContact: "21/08/26",
    reason: "Positive response both sides",
    gender: "Female",
    area: "Rohini",
    education: "B.Com",
    incomeLpa: 28,
    probability: "low",
  },
  {
    id: 6,
    name: "Disha Dubey",
    clientId: "MML-D-10253",
    phone: "******9021",
    status: "Active",
    married: false,
    address: "*********** Rajouri Garden, New Delhi",
    owner: "Rohit Kumar",
    branch: "Rajouri Garden",
    lastContact: "21/08/26",
    reason: "Negotiating 10% discount",
    gender: "Female",
    area: "Rajouri Garden",
    education: "B.Tech - IIT",
    incomeLpa: 48,
    probability: "high",
  },
  {
    id: 7,
    name: "Virat Sharma",
    clientId: "MML-D-10254",
    phone: "******6155",
    status: "Active",
    married: false,
    address: "*********** Rajouri Garden, New Delhi",
    owner: "Rohit Kumar",
    branch: "Rajouri Garden",
    lastContact: "21/08/26",
    reason: "Negotiating 10% discount",
    gender: "Male",
    area: "Rajouri Garden",
    education: "B.Tech - IIT",
    incomeLpa: 55,
    probability: "medium",
  },
  {
    id: 8,
    name: "Niharika Jain",
    clientId: "MML-D-10255",
    phone: "******2287",
    status: "Active",
    married: true,
    address: "*********** Vasant Kunj, New Delhi",
    owner: "Pooja Sharma",
    branch: "Gurgaon",
    lastContact: "18/08/26",
    reason: "Waiting on family approval",
    gender: "Female",
    area: "Rohini",
    education: "MBA - IIM",
    incomeLpa: 41,
    probability: "high",
  },
  {
    id: 9,
    name: "Arjun Mehta",
    clientId: "MML-D-10256",
    phone: "******8140",
    status: "Inactive",
    married: false,
    address: "*********** South Extension, New Delhi",
    owner: "Nikhil Bansal",
    branch: "South Extension",
    lastContact: "15/08/26",
    reason: "Follow-up scheduled next week",
    gender: "Male",
    area: "South Extension",
    education: "B.Tech - IIT",
    incomeLpa: 38,
    probability: "low",
  },
];

export const PROBABILITY_META = {
  low: { label: "Low Probability", color: "#DC2626" },
  medium: { label: "Medium", color: "#D97706" },
  high: { label: "High", color: "#16A34A" },
};

export const BRANCHES = [...new Set(CLIENTS.map((c) => c.branch))];
