export const CLIENTS = [
  {
    id: 1,
    name: "Harshit Sharma",
    clientId: "MML-D-10248",
    phone: "******4598",
    status: "Inactive",
    married: false,
    address: "*********** Vasant Kunj, New Delhi",
    owner: "Rohit Kumar",
    branch: "South Extension",
    lastContact: "21/08/26",
    reason: "Negotiating 10% discount",
    gender: "Male",
    area: "South Extension",
    education: "B.Tech",
    incomeLpa: 32,
    probability: "low",
  },
  {
    id: 2,
    name: "Aditi Gupta",
    clientId: "MML-D-10249",
    phone: "******4598",
    status: "Inactive",
    married: true,
    address: "*********** Vasant Kunj, New Delhi",
    owner: "Rohit Kumar",
    branch: "Rajouri Garden",
    lastContact: "21/08/26",
    reason: "Hand Over, Match confirmed",
    gender: "Female",
    area: "Rajouri Garden",
    education: "MBA - IIM",
    incomeLpa: 45,
    probability: "medium",
  },
  {
    id: 3,
    name: "Aslesha Singh",
    clientId: "MML-D-10250",
    phone: "******4412",
    status: "Active",
    married: false,
    address: "*********** Rohini, New Delhi",
    owner: "Rohit Kumar",
    branch: "Gurgaon",
    lastContact: "21/08/26",
    reason: "Comparing package benefits",
    gender: "Female",
    area: "Rohini",
    education: "MBA - IIM",
    incomeLpa: 52,
    probability: "high",
  },
  {
    id: 4,
    name: "Aanchal Verma",
    clientId: "MML-D-10251",
    phone: "******7781",
    status: "Inactive",
    married: true,
    address: "*********** JLT, Dubai",
    owner: "Rohit Kumar",
    branch: "Dubai",
    lastContact: "21/08/26",
    reason: "Advance received",
    gender: "Female",
    area: "Dubai",
    education: "MBBS",
    incomeLpa: 60,
    probability: "medium",
  },
  {
    id: 5,
    name: "Khushi Kumari",
    clientId: "MML-D-10252",
    phone: "******3304",
    status: "Inactive",
    married: false,
    address: "*********** Rohini, New Delhi",
    owner: "Rohit Kumar",
    branch: "South Extension",
    lastContact: "21/08/26",
    reason: "Positive response both sides",
    gender: "Female",
    area: "Rohini",
    education: "B.Com",
    incomeLpa: 28,
    probability: "low",
  },
  {
    id: 6,
    name: "Disha Dubey",
    clientId: "MML-D-10253",
    phone: "******9021",
    status: "Active",
    married: false,
    address: "*********** Rajouri Garden, New Delhi",
    owner: "Rohit Kumar",
    branch: "Rajouri Garden",
    lastContact: "21/08/26",
    reason: "Negotiating 10% discount",
    gender: "Female",
    area: "Rajouri Garden",
    education: "B.Tech - IIT",
    incomeLpa: 48,
    probability: "high",
  },
  {
    id: 7,
    name: "Virat Sharma",
    clientId: "MML-D-10254",
    phone: "******6155",
    status: "Active",
    married: false,
    address: "*********** Rajouri Garden, New Delhi",
    owner: "Rohit Kumar",
    branch: "Rajouri Garden",
    lastContact: "21/08/26",
    reason: "Negotiating 10% discount",
    gender: "Male",
    area: "Rajouri Garden",
    education: "B.Tech - IIT",
    incomeLpa: 55,
    probability: "medium",
  },
  {
    id: 8,
    name: "Niharika Jain",
    clientId: "MML-D-10255",
    phone: "******2287",
    status: "Active",
    married: true,
    address: "*********** Vasant Kunj, New Delhi",
    owner: "Pooja Sharma",
    branch: "Gurgaon",
    lastContact: "18/08/26",
    reason: "Waiting on family approval",
    gender: "Female",
    area: "Rohini",
    education: "MBA - IIM",
    incomeLpa: 41,
    probability: "high",
  },
  {
    id: 9,
    name: "Arjun Mehta",
    clientId: "MML-D-10256",
    phone: "******8140",
    status: "Inactive",
    married: false,
    address: "*********** South Extension, New Delhi",
    owner: "Nikhil Bansal",
    branch: "South Extension",
    lastContact: "15/08/26",
    reason: "Follow-up scheduled next week",
    gender: "Male",
    area: "South Extension",
    education: "B.Tech - IIT",
    incomeLpa: 38,
    probability: "low",
  },
  {
    id: 10,
    name: "Priya Malhotra",
    clientId: "MML-D-10257",
    phone: "******1203",
    status: "Active",
    married: false,
    address: "*********** Defence Colony, New Delhi",
    owner: "Pooja Sharma",
    branch: "South Extension",
    lastContact: "20/08/26",
    reason: "Profile shared with 3 matches",
    gender: "Female",
    area: "South Extension",
    education: "CA",
    incomeLpa: 36,
    probability: "high",
  },
  {
    id: 11,
    name: "Rohan Kapoor",
    clientId: "MML-D-10258",
    phone: "******5642",
    status: "Active",
    married: false,
    address: "*********** Cyber City, Gurgaon",
    owner: "Nikhil Bansal",
    branch: "Gurgaon",
    lastContact: "19/08/26",
    reason: "Interested in premium package",
    gender: "Male",
    area: "Gurgaon",
    education: "MBA - ISB",
    incomeLpa: 72,
    probability: "high",
  },
  {
    id: 12,
    name: "Sneha Reddy",
    clientId: "MML-D-10259",
    phone: "******8831",
    status: "Inactive",
    married: true,
    address: "*********** Marina, Dubai",
    owner: "Rohit Kumar",
    branch: "Dubai",
    lastContact: "12/08/26",
    reason: "On hold — relocating",
    gender: "Female",
    area: "Dubai",
    education: "M.Tech",
    incomeLpa: 58,
    probability: "low",
  },
  {
    id: 13,
    name: "Kabir Singh",
    clientId: "MML-D-10260",
    phone: "******4019",
    status: "Active",
    married: false,
    address: "*********** Punjabi Bagh, New Delhi",
    owner: "Pooja Sharma",
    branch: "Rajouri Garden",
    lastContact: "22/08/26",
    reason: "Meeting booked this weekend",
    gender: "Male",
    area: "Rajouri Garden",
    education: "B.Tech",
    incomeLpa: 42,
    probability: "medium",
  },
  {
    id: 14,
    name: "Ananya Chopra",
    clientId: "MML-D-10261",
    phone: "******7720",
    status: "Active",
    married: false,
    address: "*********** Saket, New Delhi",
    owner: "Rohit Kumar",
    branch: "South Extension",
    lastContact: "21/08/26",
    reason: "Family shortlist ready",
    gender: "Female",
    area: "South Extension",
    education: "MBA",
    incomeLpa: 39,
    probability: "high",
  },
  {
    id: 15,
    name: "Devansh Agarwal",
    clientId: "MML-D-10262",
    phone: "******3398",
    status: "Inactive",
    married: false,
    address: "*********** Sector 56, Gurgaon",
    owner: "Nikhil Bansal",
    branch: "Gurgaon",
    lastContact: "10/08/26",
    reason: "No response after 2 follow-ups",
    gender: "Male",
    area: "Gurgaon",
    education: "B.Com",
    incomeLpa: 24,
    probability: "low",
  },
  {
    id: 16,
    name: "Meera Iyer",
    clientId: "MML-D-10263",
    phone: "******5514",
    status: "Active",
    married: true,
    address: "*********** Pitampura, New Delhi",
    owner: "Pooja Sharma",
    branch: "Rohini",
    lastContact: "23/08/26",
    reason: "Awaiting biodata update",
    gender: "Female",
    area: "Rohini",
    education: "MBBS",
    incomeLpa: 65,
    probability: "medium",
  },
  {
    id: 17,
    name: "Ishaan Bhatia",
    clientId: "MML-D-10264",
    phone: "******9088",
    status: "Active",
    married: false,
    address: "*********** Business Bay, Dubai",
    owner: "Rohit Kumar",
    branch: "Dubai",
    lastContact: "20/08/26",
    reason: "Premium enquiry — NRI",
    gender: "Male",
    area: "Dubai",
    education: "MS - USA",
    incomeLpa: 95,
    probability: "high",
  },
  {
    id: 18,
    name: "Riya Saxena",
    clientId: "MML-D-10265",
    phone: "******2167",
    status: "Inactive",
    married: false,
    address: "*********** Karol Bagh, New Delhi",
    owner: "Nikhil Bansal",
    branch: "Rajouri Garden",
    lastContact: "08/08/26",
    reason: "Budget mismatch",
    gender: "Female",
    area: "Rajouri Garden",
    education: "BA",
    incomeLpa: 18,
    probability: "low",
  },
  {
    id: 19,
    name: "Yash Thakur",
    clientId: "MML-D-10266",
    phone: "******6443",
    status: "Active",
    married: false,
    address: "*********** Greater Kailash, New Delhi",
    owner: "Pooja Sharma",
    branch: "South Extension",
    lastContact: "22/08/26",
    reason: "Second meeting confirmed",
    gender: "Male",
    area: "South Extension",
    education: "B.Tech - NIT",
    incomeLpa: 44,
    probability: "medium",
  },
  {
    id: 20,
    name: "Kavya Nair",
    clientId: "MML-D-10267",
    phone: "******1785",
    status: "Active",
    married: true,
    address: "*********** DLF Phase 2, Gurgaon",
    owner: "Rohit Kumar",
    branch: "Gurgaon",
    lastContact: "21/08/26",
    reason: "Match interest mutual",
    gender: "Female",
    area: "Gurgaon",
    education: "MBA - XLRI",
    incomeLpa: 54,
    probability: "high",
  },
  {
    id: 21,
    name: "Siddharth Rao",
    clientId: "MML-D-10268",
    phone: "******3902",
    status: "Inactive",
    married: false,
    address: "*********** Model Town, New Delhi",
    owner: "Nikhil Bansal",
    branch: "Rohini",
    lastContact: "05/08/26",
    reason: "Moved to common pool",
    gender: "Male",
    area: "Rohini",
    education: "BBA",
    incomeLpa: 22,
    probability: "low",
  },
  {
    id: 22,
    name: "Tanya Bajaj",
    clientId: "MML-D-10269",
    phone: "******7256",
    status: "Active",
    married: false,
    address: "*********** Janakpuri, New Delhi",
    owner: "Pooja Sharma",
    branch: "Rajouri Garden",
    lastContact: "19/08/26",
    reason: "Documents pending verification",
    gender: "Female",
    area: "Rajouri Garden",
    education: "M.Sc",
    incomeLpa: 31,
    probability: "medium",
  },
  {
    id: 23,
    name: "Aarav Khanna",
    clientId: "MML-D-10270",
    phone: "******4810",
    status: "Active",
    married: false,
    address: "*********** Palm Jumeirah, Dubai",
    owner: "Rohit Kumar",
    branch: "Dubai",
    lastContact: "23/08/26",
    reason: "Video call with family done",
    gender: "Male",
    area: "Dubai",
    education: "MBA - LBS",
    incomeLpa: 110,
    probability: "high",
  },
  {
    id: 24,
    name: "Pooja Desai",
    clientId: "MML-D-10271",
    phone: "******8534",
    status: "Inactive",
    married: true,
    address: "*********** Lajpat Nagar, New Delhi",
    owner: "Nikhil Bansal",
    branch: "South Extension",
    lastContact: "11/08/26",
    reason: "Paused by client request",
    gender: "Female",
    area: "South Extension",
    education: "B.Des",
    incomeLpa: 27,
    probability: "low",
  },
  {
    id: 25,
    name: "Manav Joshi",
    clientId: "MML-D-10272",
    phone: "******2671",
    status: "Active",
    married: false,
    address: "*********** Sector 45, Gurgaon",
    owner: "Pooja Sharma",
    branch: "Gurgaon",
    lastContact: "20/08/26",
    reason: "Comparing 2 shortlisted profiles",
    gender: "Male",
    area: "Gurgaon",
    education: "B.Tech - BITS",
    incomeLpa: 49,
    probability: "medium",
  },
  {
    id: 26,
    name: "Shreya Banerjee",
    clientId: "MML-D-10273",
    phone: "******6148",
    status: "Active",
    married: false,
    address: "*********** Dwarka, New Delhi",
    owner: "Rohit Kumar",
    branch: "Rohini",
    lastContact: "22/08/26",
    reason: "Strong lead — intro call done",
    gender: "Female",
    area: "Rohini",
    education: "MBA",
    incomeLpa: 37,
    probability: "high",
  },
  {
    id: 27,
    name: "Varun Sethi",
    clientId: "MML-D-10274",
    phone: "******9402",
    status: "Inactive",
    married: false,
    address: "*********** Tilak Nagar, New Delhi",
    owner: "Nikhil Bansal",
    branch: "Rajouri Garden",
    lastContact: "07/08/26",
    reason: "Cold — last contact 3 weeks ago",
    gender: "Male",
    area: "Rajouri Garden",
    education: "B.Tech",
    incomeLpa: 29,
    probability: "low",
  },
  {
    id: 28,
    name: "Isha Kapoor",
    clientId: "MML-D-10275",
    phone: "******3087",
    status: "Active",
    married: true,
    address: "*********** Vasant Vihar, New Delhi",
    owner: "Pooja Sharma",
    branch: "South Extension",
    lastContact: "21/08/26",
    reason: "Package upgrade discussion",
    gender: "Female",
    area: "South Extension",
    education: "CA",
    incomeLpa: 46,
    probability: "medium",
  },
  {
    id: 29,
    name: "Nikhil Arora",
    clientId: "MML-D-10276",
    phone: "******5729",
    status: "Active",
    married: false,
    address: "*********** Al Quoz, Dubai",
    owner: "Rohit Kumar",
    branch: "Dubai",
    lastContact: "18/08/26",
    reason: "Advance pending clearance",
    gender: "Male",
    area: "Dubai",
    education: "B.E.",
    incomeLpa: 68,
    probability: "high",
  },
  {
    id: 30,
    name: "Anvi Sharma",
    clientId: "MML-D-10277",
    phone: "******1356",
    status: "Inactive",
    married: false,
    address: "*********** Ashok Vihar, New Delhi",
    owner: "Nikhil Bansal",
    branch: "Rohini",
    lastContact: "09/08/26",
    reason: "Duplicate enquiry closed",
    gender: "Female",
    area: "Rohini",
    education: "B.Sc",
    incomeLpa: 20,
    probability: "low",
  },
  {
    id: 31,
    name: "Harsh Vardhan",
    clientId: "MML-D-10278",
    phone: "******8894",
    status: "Active",
    married: false,
    address: "*********** Golf Course Road, Gurgaon",
    owner: "Pooja Sharma",
    branch: "Gurgaon",
    lastContact: "23/08/26",
    reason: "High intent — ready to register",
    gender: "Male",
    area: "Gurgaon",
    education: "MBA - IIM",
    incomeLpa: 78,
    probability: "high",
  },
  {
    id: 32,
    name: "Simran Kaur",
    clientId: "MML-D-10279",
    phone: "******2460",
    status: "Active",
    married: false,
    address: "*********** Paschim Vihar, New Delhi",
    owner: "Rohit Kumar",
    branch: "Rajouri Garden",
    lastContact: "20/08/26",
    reason: "Parents want more profiles",
    gender: "Female",
    area: "Rajouri Garden",
    education: "M.Com",
    incomeLpa: 33,
    probability: "medium",
  },
  {
    id: 33,
    name: "Aditya Nanda",
    clientId: "MML-D-10280",
    phone: "******7013",
    status: "Inactive",
    married: true,
    address: "*********** Hauz Khas, New Delhi",
    owner: "Nikhil Bansal",
    branch: "South Extension",
    lastContact: "14/08/26",
    reason: "Already engaged elsewhere",
    gender: "Male",
    area: "South Extension",
    education: "PhD",
    incomeLpa: 50,
    probability: "low",
  },
  {
    id: 34,
    name: "Neha Pillai",
    clientId: "MML-D-10281",
    phone: "******4582",
    status: "Active",
    married: false,
    address: "*********** Sector 29, Gurgaon",
    owner: "Pooja Sharma",
    branch: "Gurgaon",
    lastContact: "22/08/26",
    reason: "Soft commitment on silver plan",
    gender: "Female",
    area: "Gurgaon",
    education: "B.Tech",
    incomeLpa: 40,
    probability: "medium",
  },
  {
    id: 35,
    name: "Raghav Malhotra",
    clientId: "MML-D-10282",
    phone: "******9125",
    status: "Active",
    married: false,
    address: "*********** Sheikh Zayed Road, Dubai",
    owner: "Rohit Kumar",
    branch: "Dubai",
    lastContact: "21/08/26",
    reason: "NRI visit next month planned",
    gender: "Male",
    area: "Dubai",
    education: "MBA",
    incomeLpa: 88,
    probability: "high",
  },
  {
    id: 36,
    name: "Diya Mehra",
    clientId: "MML-D-10283",
    phone: "******3671",
    status: "Inactive",
    married: false,
    address: "*********** Shalimar Bagh, New Delhi",
    owner: "Nikhil Bansal",
    branch: "Rohini",
    lastContact: "06/08/26",
    reason: "Unreachable — common pool",
    gender: "Female",
    area: "Rohini",
    education: "BA Honours",
    incomeLpa: 16,
    probability: "low",
  },
];

export const PROBABILITY_META = {
  low: { label: "Low Probability", color: "#DC2626" },
  medium: { label: "Medium", color: "#D97706" },
  high: { label: "High", color: "#16A34A" },
};

export const BRANCHES = [...new Set(CLIENTS.map((c) => c.branch))];
